on:
  - push

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
        racket-variant: ['BC', 'CS']
        racket-version: ['7.8', '7.9', '8.0']
    name: Test on Racket ${{ matrix.racket-variant }} ${{ matrix.racket-version }} on ${{ matrix.os }}	
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Install nasm
      run: sudo apt-get install nasm
    - name: Install libunistring
      run: |
        sudo apt-get install libunistring2
        sudo apt-get install libunistring-dev
    - name: Install Racket
      uses: Bogdanp/setup-racket@v1.1
      with:
        architecture: 'x64'
        distribution: 'full'
        variant: ${{ matrix.racket-variant }}
        version: ${{ matrix.racket-version }}
    - name: Version info
      run: |
        nasm --version
        gcc --version        
    - name: Install langs package
      run: raco pkg install ../the-838e-compiler/
    - name: Install g++
      run: sudo apt -y install g++
    - name: Install cmake
      run: sudo apt-get -y install cmake
    - name: Install wabt
      run: |
        cd ..
        git clone --recursive https://github.com/WebAssembly/wabt
        cd wabt
        mkdir build
        cd build
        cmake ..
        cmake --build .
        cd ..
        export PATH="$(pwd)/bin:$PATH"
        echo 'export PATH="'$(pwd)'/bin:$PATH"' >> ~/.bashrc
    - name: Install nodejs
      run: |
        sudo apt -y install nodejs
        which nodejs
    - name: Install wasmtime
      run: |
        curl https://wasmtime.dev/install.sh -sSf | bash
        which wasmtime
    - name: Run tests
      run: |
        pwd
        export PATH="/home/runner/work/the-838e-compiler/wabt/bin:$PATH"
        echo $PATH
        raco test -p the-838e-compiler
